## CS559: Homework #1

Assignment #1: due on **2/23/2021 by 11:59 PM**. 
- Change the file name as *YourName*_S21_CS559_HW1
- Submit the assignment both in format of *ipynb* and *html*. 
    - You can export the file as *html* as `File`>`Download as`>`HTML`. The assignment should be own work and must not be shared between classmates. 
- You **do not need to compress** the files. You can submit individual files.
- This assignment focuses on two topics - linear algebra and data pre-processing. 
    - For linear algebra questions, when the question says "implement", you cannot use any built-in functions.
- This assignment should an individual work. Do not collaborate with classmates or get help from 3rd person. You may surf internet if you need to. Then site the reference. 

### Problem 1 [10 pts]
- Implement a function `dot_product` to calculate the dot product of two 1 by n arrays. [6 pts] 
```
a = array([1, 2, 3, 4])
b = array([2, 3, 4, 5])
dot_product(a,b) = 40
```

In [108]:
import numpy as np
def dot_product(a,b):
    if(len(a)==len(b)):
        return sum(a*(b.T))   
    else:
        print("input error")   

- Test your code after generating two random 1 by 10 arrays. [4 pts]

In [109]:
import numpy as np
a = np.random.rand((10))
b = np.random.rand((10))
print (a)
print (b)
print(dot_product(a,b))
print(a.dot(b.T))

[0.49121096 0.7570717  0.19571106 0.31846293 0.25993825 0.74339835
 0.24748727 0.94842459 0.28799017 0.81645951]
[0.63067767 0.00546353 0.71982869 0.17310294 0.78398698 0.31052494
 0.73129229 0.74234243 0.65810214 0.97930055]
2.8186968559780343
2.8186968559780343


### Problem 2 [10 pts]
- Consider three vectors ${\bf x}_1=(1,3), {\bf x}_2=(-1,5)$, and ${\bf x}_3=(0,7)$. Find the distance of each point from the **origin**. [4 pts]

In [585]:
x0 = np.array([0, 0])
x1 = np.array([1, 3])
dist1 = np.sqrt(np.sum(np.square(x1 - x0)))
print("dist1 =",dist1)
x2 = np.array([-1, 5])
print("dist2 =",np.linalg.norm(x2 - x0))
x3 = np.array([0,7])
print("dist3 =",np.linalg.norm(x3))

dist1 = 3.1622776601683795
dist2 = 5.0990195135927845
dist3 = 7.0


- Rotate the coordinates by 35 degress in counter clockwise. [4 pts]

In [586]:
import math

def rotate_counter(m,x,y):
    a = x*math.cos(math.radians(m))+y*math.sin(math.radians(m))
    b = y*math.cos(math.radians(m))-x*math.sin(math.radians(m))
    return (a,b)

print ("x1 =",rotate_counter(35,1,3))
print ("x2 =",rotate_counter(35,-1,5))
print ("x3 =",rotate_counter(35,0,7))

# when I test the function with 90 degress, the value of x4 is not (7,0).
# so I test math.cos(math.radians(90)), the value is almost 0.
# Do I need to format the result or just keep it?
print ("x4 =",rotate_counter(90,0,7))
c = math.cos(math.radians(90))
print("c =",c)

x1 = (2.53988135334213, 1.8838796965159292)
x2 = (2.0487301374662383, 4.669336657796005)
x3 = (4.015035054457322, 5.7340643100229425)
x4 = (7.0, 4.286263797015736e-16)
c = 6.123233995736766e-17


- Magnify the area by 4 times. [2 pts]

In [590]:
t = math.sqrt(4)
print(t*x1)
print(t*x2)
print(t*x3)

[2. 6.]
[-2. 10.]
[ 0. 14.]


### Problem 3 [20 pts]
- Implement a function `mat_product` to calculate the matrix product of two n by n arrays. [8 pts] For example:


$A = \begin{bmatrix} 1 & 3 & 0 \\ 2 & 0 & 2 \\ 1 & 1 & 4 \end{bmatrix}$ and $A\cdot A=\begin{bmatrix} 7 & 3 & 6 \\ 4 & 8 & 8 \\ 7 & 8 & 18 \end{bmatrix}$

    mat_product(A,A)=?

In [568]:
import numpy as np
def mat_product(x,y):
        row_x = len(x)
        column_x =  len(x[0])
        column_y = len(y[0])
        row_y = len(y)
        
        if(row_x == row_y and row_x == column_y and row_y == column_y):
            res_mat = [[0] * row_x for i in range(column_y)]
            for i in range(row_x):
                for j in range(column_y):
                    for k in range(row_y):
                        temp = x[i][k] * y[k][j]
                        res_mat[i][j] += temp
            return res_mat
        else:
            print("input error") 

- Test your code after generating two random 4 by 4 matrices, ${\bf X}$ and ${\bf Y}$. [4 pts]

In [576]:
x = np.random.rand(4,4)
y = np.random.rand(4,4)
print("x =", x)
print("y =", y)
print("res_mat =", mat_product(x,y))
print("x.dot(y) =", x.dot(y))

x = [[0.80961534 0.59135705 0.70064259 0.0408807 ]
 [0.29181297 0.29914583 0.48542846 0.0617986 ]
 [0.08895299 0.30485426 0.49660299 0.00510565]
 [0.37028658 0.45465684 0.32017492 0.50306805]]
y = [[0.84728074 0.20061055 0.88192294 0.58575229]
 [0.3670103  0.18594097 0.68268043 0.1951623 ]
 [0.65151432 0.2203125  0.43137457 0.64244886]
 [0.15494848 0.15903491 0.26249367 0.7338311 ]]
res_mat = [[1.3658186983377216, 0.43323665966525143, 1.4306965419366342, 1.069771201400176], [0.6828763040684764, 0.23093831761532024, 0.6872007875126114, 0.5865247941765042], [0.5115878754491381, 0.18474962650008403, 0.5021298143482162, 0.43438917618292233], [0.767148612762735, 0.3093666489751587, 0.9071170541821301, 0.8804910819058762]]
x.dot(y) = [[1.3658187  0.43323666 1.43069654 1.0697712 ]
 [0.6828763  0.23093832 0.68720079 0.58652479]
 [0.51158788 0.18474963 0.50212981 0.43438918]
 [0.76714861 0.30936665 0.90711705 0.88049108]]


- Inplement a function `mat_transpose` that transposes ${\bf X}$ and use the `mat_product` function to find the matrice of product: $Z={\bf X}^T\cdot{\bf Y}$ [8 pts]

        Z=mat_product(mat_transpose(X),Y)

In [581]:
def mat_transpose(a):
    t = [[] for i in a[0]] 
    for ele in a:
        for i in range(len(ele)):
            t[i].append(ele[i])
    return t

X = [[1,2,3],[4,5,6],[7,8,9]]
Y = [[1,1,1],[1,1,1],[1,1,1]]
print("X_transpose =", mat_transpose(X))
Z = mat_product(mat_transpose(X),Y)
print("Z =", Z)
print((np.transpose(X)).dot(Y))

X_transpose = [[1, 4, 7], [2, 5, 8], [3, 6, 9]]
Z = [[12, 12, 12], [15, 15, 15], [18, 18, 18]]
[[12 12 12]
 [15 15 15]
 [18 18 18]]


### Problem 4 [30 pts]
- In this question, we will use the csv file **Temp.csv**. This question task is a process of exploratory data ansysis (EDA) to learn about data itself. Read it into a data frame, call it `Temp`. (Import the packages you think you need). [4 pts]

In [498]:
import pandas as pd
import numpy as np
Temp = pd.DataFrame()
Temp = pd.read_csv('Temp.csv')

- We learned that the temperature at New Haven, Connecticut is currently 58 degree fahrenheit. Add this information into the DataFrame.[4 pts]

In [499]:
print(Temp.shape) ##get row index = 7
print(list(Temp.columns))
Temp.loc[8] = ['New Heaven','Connecticut','58']
print(Temp.shape)
Temp

(7, 3)
['City', 'State', 'Temperature']
(8, 3)


City        State Temperature
0         NYC     New York          67
1      Albany     New York          49
2     Buffalo     New York          38
3    Hartford  Connecticut          63
4  Bridgeport  Connecticut          58
5      Treton   New Jersey          72
6      Newark   New Jersey          68
8  New Heaven  Connecticut          58

- Replace the names of the states by their abbreviations. [4 pts] That is 
    - Connecticut --> CT
    - New Jersey  --> NJ
    - New York    --> NY

In [500]:
Temp = Temp.replace(['Connecticut','New Jersey','New York'],['CT','NJ','NY'])
Temp

City State Temperature
0         NYC    NY          67
1      Albany    NY          49
2     Buffalo    NY          38
3    Hartford    CT          63
4  Bridgeport    CT          58
5      Treton    NJ          72
6      Newark    NJ          68
8  New Heaven    CT          58

- Select the rows in New York. [2 pts]

In [501]:
NY = Temp[Temp['State'].str.contains('NY')]
print(NY)

      City State Temperature
0      NYC    NY          67
1   Albany    NY          49
2  Buffalo    NY          38


- What is the average of the temperature of cities in NY? [4 pts]

In [502]:
average=NY["Temperature"].mean()
print("average of the temperature in NY is", average)

average of the temperature in NY is 51.333333333333336


- Find the mean and the standard deviation of the temperature of each state. [4 pts]

In [503]:
#Temp.info()
Temp['Temperature'] = Temp['Temperature'].apply(pd.to_numeric)
Temp.groupby('State').agg([np.mean, np.std])

Temperature           
             mean        std
State                       
CT      59.666667   2.886751
NJ      70.000000   2.828427
NY      51.333333  14.640128

- Create a data frame `Capital`, with two columns: State and Capital. [4 pts] 

    We know the capital of each state: 
    - Connecticut --> Hartford
    - New Jersey  --> Treton
    - New York    --> Albany
    
|| State| Capital|
| :-: |:---: | :---:|
| 0| CT  | Hartford|
| 1| NJ | Treton|
| 2| NY| Albany|

In [504]:
Capital = pd.DataFrame([['CT','Hartford'],['NJ','Treton'],['NY','Albany'],], columns=['State','Capital'])
Capital
#Capital.replace(['CT','NJ'],['TC','JN'])

State   Capital
0    CT  Hartford
1    NJ    Treton
2    NY    Albany

- Mutate a new boolean column, `Capital`, to `Temp`, which is `True` if the city in the row is the capital of the state, else `False`. [4 pts]

In [526]:
Temp['Capital'] = Temp['City'].isin(Capital['Capital'])
Temp

City State  Temperature  Capital
0         NYC    NY           67    False
1      Albany    NY           49     True
2     Buffalo    NY           38    False
3    Hartford    CT           63     True
4  Bridgeport    CT           58    False
5      Treton    NJ           72     True
6      Newark    NJ           68    False
8  New Heaven    CT           58    False

### Problem 5 [30 pts]

- a. Load the Gross Domestic Product data for the 190 ranked countries in the file **GDP.csv**. Load **Country.csv** into a DataFrame. [6 pts]

In [104]:
import pandas as pd
import numpy as np
gdp = pd.read_csv('GDP.csv',header = None,encoding='ISO-8859-1', skiprows=5, nrows = 190,usecols=[0,1,3,4],keep_default_na=False)
gdp.columns = ['CountryCode', 'Ranking','Economy','millions of US dollars']
#print(gdp)
country=pd.read_csv('Country.csv',encoding='ISO-8859-1',keep_default_na=False)
#print(country)
#print(list(gdp.columns))
#print(list(country.columns))

- b. Match the data based on the country shortcode. How many of the IDs match? [6 pts]

In [105]:
data = pd.merge(gdp, country, on='CountryCode', how='inner')
data

CountryCode  Ranking                Economy millions of US dollars  \
0           USA        1          United States            16,244,600    
1           CHN        2                  China             8,227,103    
2           JPN        3                  Japan             5,959,718    
3           DEU        4                Germany             3,428,131    
4           FRA        5                 France             2,612,878    
..          ...      ...                    ...                    ...   
184         STP      186  São Tomé and Principe                   263    
185         PLW      187                  Palau                   228    
186         MHL      188       Marshall Islands                   182    
187         KIR      189               Kiribati                   175    
188         TUV      190                 Tuvalu                    40    

                                        Long Name         Income Group  \
0                        United States of America    High income: OECD   
1                      People's Republic of China  Lower middle income   
2                                           Japan    High income: OECD   
3                     Federal Republic of Germany    High income: OECD   
4                                 French Republic    High income: OECD   
..                                            ...                  ...   
184  Democratic Republic of São Tomé and Principe  Lower middle income   
185                             Republic of Palau  Upper middle income   
186              Republic of the Marshall Islands  Lower middle income   
187                          Republic of Kiribati  Lower middle income   
188                                        Tuvalu  Lower middle income   

                    Region Lending category Other groups  \
0            North America                                 
1      East Asia & Pacific             IBRD                
2      East Asia & Pacific                                 
3    Europe & Central Asia                     Euro area   
4    Europe & Central Asia                     Euro area   
..                     ...              ...          ...   
184     Sub-Saharan Africa              IDA         HIPC   
185    East Asia & Pacific             IBRD                
186    East Asia & Pacific             IBRD                
187    East Asia & Pacific              IDA                
188    East Asia & Pacific                                 

                   Currency Unit  ...  \
0                    U.S. dollar  ...   
1                   Chinese yuan  ...   
2                   Japanese yen  ...   
3                           Euro  ...   
4                           Euro  ...   
..                           ...  ...   
184  São Tomé and Principe dobra  ...   
185                  U.S. dollar  ...   
186                  U.S. dollar  ...   
187            Australian dollar  ...   
188            Australian dollar  ...   

    Source of most recent Income and expenditure data  \
0                                            LFS 2000   
1                                           IHS, 2005   
2                                            IS, 1993   
3                                           IHS, 2000   
4                                      ES/BS, 1994/95   
..                                                ...   
184                                        PS 2000-01   
185                                                     
186                                                     
187                                                     
188                                                     

    Vital registration complete Latest agricultural census  \
0                           Yes                  1997/2002   
1                                                     1997   
2                           Yes                       2000   
3                           Yes                  1999-2000   
4                

In [106]:
print(len(data))

189


- c. Sort the data frame in descending order by GDP rank. What is the 13th country in the resulting data frame? (Note: GDP formats as 123,456,789.) [6 pts]

In [107]:
data['millions of US dollars'] = data['millions of US dollars'].str.replace(',', '').astype(float)
newdata = data.sort_values(by='millions of US dollars',ascending=False)
#newdata.head(13)
newdata.iloc[[12]]

CountryCode  Ranking Economy  millions of US dollars         Long Name  \
12         ESP       13   Spain               1322965.0  Kingdom of Spain   

         Income Group                 Region Lending category Other groups  \
12  High income: OECD  Europe & Central Asia                     Euro area   

   Currency Unit  ... Source of most recent Income and expenditure data  \
12          Euro  ...                                         IHS, 2000   

   Vital registration complete Latest agricultural census  \
12                         Yes                       1999   

   Latest industrial data Latest trade data Latest water withdrawal data  \
12                   2004              2008                         2000   

   2-alpha code WB-2 code Table Name Short Name  
12           ES        ES      Spain      Spain  

[1 rows x 34 columns]

- d. What is the average GDP for the "High income: OECD" and "High income: nonOECD" group? [6 pts]

In [109]:
#data['millions of US dollars'] = data['millions of US dollars'].str.replace(',', '').apply(pd.to_numeric)
#data['millions of US dollars'] = data['millions of US dollars'].str.replace(',', '').astype(int)
#data.info()
data.groupby('Income Group')['millions of US dollars'].agg(np.mean)

Income Group
High income: OECD       1.483917e+06
High income: nonOECD    1.043498e+05
Low income              1.441078e+04
Lower middle income     2.566635e+05
Upper middle income     2.318478e+05
Name: millions of US dollars, dtype: float64

- e. What is the average GDP for different income groups and regions? [6 pts]

In [110]:
data.groupby([data['Income Group'],data['Region']])['millions of US dollars'].agg(np.mean)

Income Group          Region                    
High income: OECD     East Asia & Pacific           2.197268e+06
                      Europe & Central Asia         7.567044e+05
                      Middle East & North Africa    2.582170e+05
                      North America                 9.033012e+06
High income: nonOECD  East Asia & Pacific           1.496240e+05
                      Europe & Central Asia         2.776660e+04
                      Latin America & Caribbean     2.795480e+04
                      Middle East & North Africa    2.142531e+05
                      North America                 5.474000e+03
                      Sub-Saharan Africa            1.769700e+04
Low income            East Asia & Pacific           8.154667e+03
                      Europe & Central Asia         6.723500e+03
                      Latin America & Caribbean     7.843000e+03
                      South Asia                    5.193833e+04
                      Sub-Saharan Africa 